version: '2'
services:
  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_DB=jwt
      - POSTGRES_USER=safwan
      - POSTGRES_PASSWORD=Safwan@123
     
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/